#!/usr/bin/env bash

# this script will install the switch repository in a subdirectory under this one
# and then link packages from there into the current directory so they can be
# used for this study.

echo "Retrieving SWITCH repository from https://github.com/switch-model/switch.git"
git clone https://github.com/switch-model/switch.git
cd switch
git checkout hawaii
cd ..
ln -s switch/switch_mod .
ln -s switch/switch_hawaii .

echo "SWITCH has been installed; working on branch 'hawaii'."
echo "use 'python -m switch_mod.solve' to solve the current study"
echo "or 'python -m switch_mod.solve --help' for help."
