#!/bin/bash

# find out how big the job array needs to be (number of lines in scenarios.txt)
n_scens=$(wc -l scenarios.txt | awk '{ print $1 }')

echo "Queueing $n_scens scenarios from scenarios.txt"

# queue the job
sbatch --array=1-$n_scens solve_array.slurm
